use-custom-datasource: false
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:localdb
    username: sa
    password: